# Netlify configuration
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10.9.2"
  # Ensure Next.js knows the deployment URL
  NEXT_PUBLIC_SITE_URL = "${DEPLOY_PRIME_URL}"
  # Force cache clear
  NETLIFY_CACHE_BUST = "2025-07-31-security-fix"

# Branch deploy contexts
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Visual Editor configuration
[context.visual-editor]
  command = "npm run build"
  
# Visual Editor preview settings
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    
# Additional headers for Visual Editor
[[headers]]
  for = "/_next/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    
# Stackbit/Visual Editor configuration
[build.processing]
  skip_processing = false

[build.processing.css]
  minify = false

[build.processing.js]
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true